#!/bin/sh
eval $IMPORT_MADLAD

path="$@"
name="${path##*/}"

eraseall
if [ -f "$path" ]; then
    finsert "$path"
    cursor_u $(getv buf:lines)
fi
setv buf:path "$path"

case "$name" in
    *.*) filetype=${name##*.} ;;
    *)   filetype=$name ;;
esac

status

if ! setv filetype "$filetype" > /dev/null; then
    printf " (unsupported filetype)"
fi
